INFRA-4977 zombie counter
AnchorFree/docker-exporter pull request #6
Opened 2018-01-15 23:14 UTC by ahammond

2018-01-15 23:28 UTC, sund0g reviewed
Approved by me but would like additional review by @onorua and/or @white-hat

2018-01-16 00:27 UTC, white-hat requested changes

2018-01-16 00:27 UTC, white-hat commented on main.go
> +	// First, parse out the image name
please add a sample string

2018-01-16 00:27 UTC, white-hat commented on main.go
> +	d.Close()
already closed at #263

2018-01-16 01:19 UTC, ahammond commented on main.go
> +	// First, parse out the image name
Added.

2018-01-16 03:27 UTC, white-hat approved these changes

2018-01-16 03:41 UTC, merged